image: rust:latest

before_script:
- echo deb http://ftp.debian.org/debian stretch-backports main > /etc/apt/sources.list.d/backports.list
- apt-get update
- apt-get install -y -t stretch-backports libostree-dev

stages:
- build
- package

libostree-sys:
  stage: build
  script:
  - cargo build --verbose --package libostree-sys
  - cargo test --verbose --package libostree-sys

libostree-sys_release:
  stage: build
  script:
  - cargo build --verbose --release --package libostree-sys
  - cargo test --verbose --release --package libostree-sys

libostree:
  stage: build
  script:
  - cargo build --verbose --package libostree
  - cargo test --verbose --package libostree

libostree_release:
  stage: build
  script:
  - cargo build --verbose --release --package libostree
  - cargo test --verbose --release --package libostree

libostree-sys_nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
  - cargo build --verbose --package libostree-sys
  - cargo test --verbose --package libostree-sys
  allow_failure: true

libostree_nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
  - cargo build --verbose --package libostree
  - cargo test --verbose --package libostree
  allow_failure: true

libostree-sys_package:
  stage: package
  script:
    - cargo package --verbose --manifest-path libostree-sys/Cargo.toml

libostree_package:
  stage: package
  script:
  - cargo package --verbose --manifest-path libostree/Cargo.toml
