image: rust:latest

variables:
  CARGO_TARGET_DIR: target

before_script:
- echo deb http://ftp.debian.org/debian stretch-backports main > /etc/apt/sources.list.d/backports.list
- apt-get update
- apt-get install -y -t stretch-backports cmake libostree-dev

stages:
- build
- publish

# libostree-sys
libostree-sys:
  stage: build
  script:
  - cargo test --verbose --manifest-path libostree-sys/Cargo.toml

libostree-sys_nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
  - cargo test --verbose --manifest-path libostree-sys/Cargo.toml
  allow_failure: true

publish_libostree-sys:
  stage: publish
  script:
  - cargo publish --verbose --manifest-path libostree-sys/Cargo.toml --token $CRATES_IO_TOKEN
  when: manual

# libostree
libostree:
  stage: build
  script:
  - cargo test --verbose

libostree_nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
  - cargo test --verbose
  allow_failure: true

publish_libostree:
  stage: publish
  script:
  - cargo publish --verbose --token $CRATES_IO_TOKEN
  when: manual

# docs
docs:
  stage: build
  script:
  - make merge-lgpl-docs
  - cargo doc --verbose --features dox
  artifacts:
    paths:
    - target/doc

pages:
  stage: publish
  script:
  - cp -r target/doc public
  artifacts:
    paths:
    - public
  only:
  - master
