[package]
name = "ostree"
version = "0.3.0"
authors = ["Felix Krull"]

license = "MIT"
description = "Rust bindings for libostree"
keywords = ["ostree", "libostree"]

documentation = "https://fkrull.gitlab.io/ostree-rs/ostree"
repository = "https://gitlab.com/fkrull/ostree-rs"
readme = "README.md"

exclude = [
    "conf/**",
    "gir-files/**",
    "sys/**",
    ".gitlab-ci.yml",
]

[package.metadata.docs.rs]
features = ["dox"]

[badges.gitlab]
repository = "fkrull/ostree-rs"

[lib]
name = "ostree"

[dependencies]
libc = "0.2"
bitflags = "1"
lazy_static = "1.1"
glib = "0.6"
gio = "0.5"
glib-sys = "0.7"
gobject-sys = "0.7"
gio-sys = "0.7"
ostree-sys = { version = "0.3", path = "sys" }

[dev-dependencies]
tempfile = "3"

[features]
dox = ["ostree-sys/dox"]
v2014_9 = ["ostree-sys/v2014_9"]
v2015_7 = ["v2014_9", "ostree-sys/v2015_7"]
v2017_3 = ["v2015_7", "ostree-sys/v2017_3"]
v2017_4 = ["v2017_3", "ostree-sys/v2017_4"]
v2017_6 = ["v2017_4", "ostree-sys/v2017_6"]
v2017_7 = ["v2017_6", "ostree-sys/v2017_7"]
v2017_8 = ["v2017_7", "ostree-sys/v2017_8"]
v2017_9 = ["v2017_8", "ostree-sys/v2017_9"]
v2017_10 = ["v2017_9", "ostree-sys/v2017_10"]
v2017_11 = ["v2017_10", "ostree-sys/v2017_11"]
v2017_12 = ["v2017_11", "ostree-sys/v2017_12"]
v2017_13 = ["v2017_12", "ostree-sys/v2017_13"]
v2017_15 = ["v2017_13", "ostree-sys/v2017_15"]
v2018_2 = ["v2017_15", "ostree-sys/v2018_2"]
v2018_3 = ["v2018_2", "ostree-sys/v2018_3"]
v2018_5 = ["v2018_3", "ostree-sys/v2018_5"]
v2018_6 = ["v2018_5", "ostree-sys/v2018_6"]
v2018_7 = ["v2018_6", "ostree-sys/v2018_7"]
v2018_9 = ["v2018_7", "ostree-sys/v2018_9"]
v2019_2 = ["v2018_9", "ostree-sys/v2019_2"]
