[package]
name = "libostree"
version = "0.2.0"

[lib]
name = "libostree"

[dependencies]
glib = "^0.6.0"
gio = "^0.5.0"
glib-sys = "^0.7"
gobject-sys = "^0.7"
libostree-sys = { path = "../libostree-sys" }
