[options]
work_mode = "normal"
library = "OSTree"
version = "1.0"
target_path = "../libostree"
deprecate_by_min_version = true
single_version_file = true

girs_dir = "../gir-files"

generate = [
    "OSTree.RepoMode",
    "OSTree.ObjectType",
]

[[object]]
name = "OSTree.Repo"
status = "generate"
    [[object.function]]
    pattern = ".+_async"
    ignore = true
