[options]
work_mode = "normal"
library = "OSTree"
version = "1.0"
target_path = "../libostree"
deprecate_by_min_version = true
single_version_file = true

girs_dir = "../gir-files"

generate = [
    "OSTree.RepoMode",
    "OSTree.ObjectType",
]

manual = [
    "GLib.Error",
    "GLib.Variant",
    "Gio.Cancellable",
    "Gio.File",

    #"OSTree.RepoCheckoutAtOptions",
]

[[object]]
name = "OSTree.Repo"
status = "generate"
    [[object.function]]
    pattern = ".+_async"
    ignore = true

    [[object.function]]
    pattern = "checkout_at"
        [[object.function.parameter]]
        name = "options"
        const = true

    [[object.function]]
    pattern = "mode_from_string"
    ignore = true
