[options]
work_mode = "normal"
library = "OSTree"
version = "1.0"
target_path = ".."
doc_target_path = "../target/vendor.md"
deprecate_by_min_version = true
single_version_file = true
generate_display_trait = true

girs_dir = "../gir-files"

generate = [
    "OSTree.AsyncProgress",
    "OSTree.BootconfigParser",
    "OSTree.Deployment",
    "OSTree.DeploymentUnlockedState",
    "OSTree.GpgSignatureFormatFlags",
    "OSTree.GpgVerifyResult",
    "OSTree.MutableTree",
    "OSTree.ObjectType",
    "OSTree.Remote",
    "OSTree.RepoCheckoutMode",
    "OSTree.RepoCheckoutOverwriteMode",
    "OSTree.RepoCommitModifier",
    "OSTree.RepoCommitState",
    "OSTree.RepoDevInoCache",
    "OSTree.RepoFile",
    "OSTree.RepoListRefsExtFlags",
    "OSTree.RepoMode",
    "OSTree.RepoPruneFlags",
    "OSTree.RepoPullFlags",
    "OSTree.RepoRemoteChange",
    "OSTree.RepoResolveRevExtFlags",
    "OSTree.RepoTransactionStats",
    "OSTree.SePolicy",
    "OSTree.SePolicyRestoreconFlags",
    "OSTree.StaticDeltaGenerateOpt",
    "OSTree.Sysroot",
    "OSTree.SysrootSimpleWriteDeploymentFlags",
    "OSTree.SysrootUpgrader",
    "OSTree.SysrootUpgraderFlags",
    "OSTree.SysrootUpgraderPullFlags",

    #"OSTree.RepoPruneOptions",
    #"OSTree.RepoExportArchiveOptions",
    #"OSTree.RepoCheckoutOptions",
    #"OSTree.RepoCheckoutAtOptions",
]

manual = [
    "Gio.Cancellable",
    "Gio.File",
    "Gio.FileInfo",
    "Gio.FileQueryInfoFlags",
    "Gio.InputStream",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.KeyFile",
    "GLib.String",
    "GLib.Variant",
]

[crate_name_overrides]
os_tree = "ostree"

[[object]]
name = "OSTree.CollectionRef"
status = "generate"
    [[object.function]]
    # helper functions for NULL-terminated arrays
    pattern = "dupv|freev"
    ignore = true

    [[object.function]]
    # we get this for free, I think?
    name = "dup"
    ignore = true

[[object]]
name = "OSTree.Repo"
status = "generate"
manual_traits = ["RepoExtManual"]
    [[object.function]]
    # crashes while generating, not sure what's wrong with this; might be a gir issue
    name = "write_metadata_async"
    ignore = true

    [[object.function]]
    # issue with the return type of content (thinks guchar** is u8)
    name = "write_content_async"
    ignore = true

[[object]]
name = "OSTree.*"
status = "generate"
    [[object.function]]
    # both too low-level to be generated safely
    pattern = "cmp_checksum_bytes|checksum_inplace_to_bytes"
    ignore = true

    [[object.constant]]
    # version-dependent constants
    pattern = "VERSION|VERSION_S|YEAR_VERSION|RELEASE_VERSION"
    ignore = true
