[options]
work_mode = "normal"
library = "OSTree"
version = "1.0"
target_path = ".."
doc_target_path = "../target/vendor.md"
deprecate_by_min_version = true
single_version_file = true
generate_display_trait = true

girs_dir = "../gir-files"

generate = [
    "OSTree.AsyncProgress",
    "OSTree.BootconfigParser",
    "OSTree.ChecksumFlags",
    "OSTree.Deployment",
    "OSTree.DeploymentUnlockedState",
    "OSTree.DiffFlags",
    "OSTree.DiffItem",
    "OSTree.GpgSignatureAttr",
    "OSTree.GpgSignatureFormatFlags",
    "OSTree.GpgVerifyResult",
    "OSTree.MutableTree",
    "OSTree.ObjectType",
    "OSTree.Remote",
    "OSTree.RepoCheckoutFilterResult",
    "OSTree.RepoCheckoutMode",
    "OSTree.RepoCheckoutOverwriteMode",
    "OSTree.RepoCommitModifier",
    "OSTree.RepoCommitState",
    "OSTree.RepoDevInoCache",
    "OSTree.RepoFile",
    "OSTree.RepoFinder",
    "OSTree.RepoListRefsExtFlags",
    "OSTree.RepoMode",
    "OSTree.RepoPruneFlags",
    "OSTree.RepoPullFlags",
    "OSTree.RepoRemoteChange",
    "OSTree.RepoResolveRevExtFlags",
    "OSTree.RepoTransactionStats",
    "OSTree.SePolicy",
    "OSTree.SePolicyRestoreconFlags",
    "OSTree.StaticDeltaGenerateOpt",
    "OSTree.Sysroot",
    "OSTree.SysrootSimpleWriteDeploymentFlags",
    "OSTree.SysrootUpgrader",
    "OSTree.SysrootUpgraderFlags",
    "OSTree.SysrootUpgraderPullFlags",

    #"OSTree.RepoPruneOptions",
    #"OSTree.RepoExportArchiveOptions",
]

manual = [
    "Gio.Cancellable",
    "Gio.File",
    "Gio.FileInfo",
    "Gio.FileQueryInfoFlags",
    "Gio.InputStream",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.KeyFile",
    "GLib.String",
    "GLib.Variant",

    "OSTree.RepoCheckoutAtOptions",
]

[crate_name_overrides]
os_tree = "ostree"

[[object]]
name = "OSTree.CollectionRef"
status = "generate"
    [[object.function]]
    # helper functions for NULL-terminated arrays
    pattern = "dupv|freev"
    ignore = true

    [[object.function]]
    # clone() should already be this
    name = "dup"
    ignore = true

[[object]]
name = "OSTree.Repo"
status = "generate"
    [[object.function]]
    # these all don't generate properly
    pattern = "write_metadata_async|write_content_async|pull_from_remotes_async|find_remotes_async"
    ignore = true

    [[object.function]]
    # this is deprecated and supposedly unsafe for GI
    name = "checkout_tree_at"
    ignore = true

    [[object.function]]
    # TODO: see which of these annotations I can upstream
    name = "checkout_at"
    [[object.function.parameter]]
    name = "options"
    const = true
    [[object.function.parameter]]
    name = "destination_path"
    string_type = "filename"

[[object]]
name = "OSTree.RepoFinderResult"
status = "generate"
    [[object.function]]
    # array helper function
    name = "freev"
    ignore = true

    [[object.function]]
    # clone() should already be this
    name = "dup"
    ignore = true

[[object]]
name = "OSTree.*"
status = "generate"
    [[object.function]]
    # both too low-level to be generated safely
    pattern = "cmp_checksum_bytes|checksum_inplace_to_bytes"
    ignore = true

    [[object.constant]]
    # version-dependent constants
    pattern = "VERSION|VERSION_S|YEAR_VERSION|RELEASE_VERSION"
    ignore = true
