[options]
work_mode = "normal"
library = "OSTree"
version = "1.0"
target_path = ".."
doc_target_path = "../target/vendor.md"
deprecate_by_min_version = true
single_version_file = true
generate_display_trait = true

girs_dir = "../gir-files"

generate = [
    "OSTree.AsyncProgress",
    "OSTree.GpgSignatureFormatFlags",
    "OSTree.GpgVerifyResult",
    "OSTree.ObjectType",
    "OSTree.Remote",
    "OSTree.RepoCheckoutMode",
    "OSTree.RepoCheckoutOverwriteMode",
    "OSTree.RepoCommitModifier",
    "OSTree.RepoCommitState",
    "OSTree.RepoDevInoCache",
    "OSTree.RepoMode",
    "OSTree.RepoPruneFlags",
    "OSTree.RepoPullFlags",
    "OSTree.RepoRemoteChange",
    "OSTree.RepoResolveRevExtFlags",
    "OSTree.RepoTransactionStats",
    "OSTree.SePolicy",
    "OSTree.SePolicyRestoreconFlags",
    "OSTree.StaticDeltaGenerateOpt",
    "OSTree.RepoListRefsExtFlags",

    #"OSTree.RepoPruneOptions",
    #"OSTree.RepoExportArchiveOptions",
    #"OSTree.RepoCheckoutOptions",
    #"OSTree.RepoCheckoutAtOptions",
]

manual = [
    "Gio.Cancellable",
    "Gio.File",
    "Gio.FileInfo",
    "Gio.FileQueryInfoFlags",
    "Gio.InputStream",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.KeyFile",
    "GLib.String",
    "GLib.Variant",
]

[[object]]
name = "OSTree.CollectionRef"
status = "manual"
    [[object.function]]
    # helper functions for NULL-terminated arrays
    pattern = "dupv|freev"
    ignore = true

    [[object.function]]
    # we get this for free?
    name = "dup"
    ignore = true

[[object]]
name = "OSTree.MutableTree"
status = "generate"
    [[object.function]]
    pattern = "lookup"
    ignore = true

[[object]]
name = "OSTree.Repo"
status = "generate"
    [[object.function]]
    pattern = ".+_async"
    ignore = true

    [[object.function]]
    pattern = "mode_from_string"
    ignore = true

    [[object.function]]
    pattern = "remote_gpg_import"
    ignore = true

[[object]]
name = "OSTree.RepoFile"
status = "generate"
    [[object.function]]
    pattern = "get_xattrs"
    ignore = true

    [[object.function]]
    pattern = "tree_find_child"
    ignore = true

    [[object.function]]
    pattern = "tree_query_child"
    ignore = true

[[object]]
name = "OSTree.*"
status = "generate"
    [[object.function]]
    pattern = "cmp_checksum_bytes|checksum_inplace_to_bytes"
    ignore = true

    [[object.constant]]
    pattern = "VERSION|VERSION_S|YEAR_VERSION|RELEASE_VERSION"
    ignore = true
