[options]
work_mode = "normal"
library = "OSTree"
version = "1.0"
target_path = ".."
doc_target_path = "../target/vendor.md"
deprecate_by_min_version = true
single_version_file = true
generate_display_trait = true

girs_dir = "../gir-files"

generate = [
    "OSTree.AsyncProgress",
    "OSTree.BootconfigParser",
    "OSTree.ChecksumFlags",
    "OSTree.CommitSizesEntry",
    "OSTree.Deployment",
    "OSTree.DeploymentUnlockedState",
    "OSTree.DiffFlags",
    "OSTree.DiffItem",
    "OSTree.GpgSignatureAttr",
    "OSTree.GpgSignatureFormatFlags",
    "OSTree.GpgVerifyResult",
    "OSTree.MutableTree",
    "OSTree.ObjectType",
    "OSTree.Remote",
    "OSTree.RepoCheckoutFilterResult",
    "OSTree.RepoCheckoutMode",
    "OSTree.RepoCheckoutOverwriteMode",
    "OSTree.RepoCommitFilterResult",
    "OSTree.RepoCommitFilter",
    "OSTree.RepoCommitIterResult",
    "OSTree.RepoCommitModifierFlags",
    "OSTree.RepoCommitTraverseFlags",
    "OSTree.RepoCommitModifier",
    "OSTree.RepoCommitState",
    "OSTree.RepoDevInoCache",
    "OSTree.RepoFile",
    "OSTree.RepoFinderAvahi",
    "OSTree.RepoFinderConfig",
    "OSTree.RepoFinderMount",
    "OSTree.RepoFinderOverride",
    "OSTree.RepoListObjectsFlags",
    "OSTree.RepoListRefsExtFlags",
    "OSTree.RepoMode",
    "OSTree.RepoPruneFlags",
    "OSTree.RepoPullFlags",
    "OSTree.RepoRemoteChange",
    "OSTree.RepoResolveRevExtFlags",
    "OSTree.SePolicy",
    "OSTree.SePolicyRestoreconFlags",
    "OSTree.StaticDeltaGenerateOpt",
    "OSTree.Sysroot",
    "OSTree.SysrootSimpleWriteDeploymentFlags",
    "OSTree.SysrootUpgrader",
    "OSTree.SysrootUpgraderFlags",
    "OSTree.SysrootUpgraderPullFlags",
]

manual = [
    # types from glib/gio we need
    "Gio.AsyncReadyCallback",
    "Gio.AsyncResult",
    "Gio.Cancellable",
    "Gio.File",
    "Gio.FileInfo",
    "Gio.FileQueryInfoFlags",
    "Gio.FilterInputStream",
    "Gio.InputStream",
    "Gio.VolumeMonitor",
    "GLib.Bytes",
    "GLib.Checksum",
    "GLib.DestroyNotify",
    "GLib.Error",
    "GLib.KeyFile",
    "GLib.MainContext",
    "GLib.Quark",
    "GLib.String",
    "GLib.Variant",
    "GLib.VariantType",

    # types implemented by hand
    "OSTree.KernelArgs",
    "OSTree.RepoCheckoutAtOptions",
    "OSTree.RepoCheckoutFilter",
]

ignore = [
    # only used for the already-deprecated checkout_tree_at function
    "OSTree.RepoCheckoutOptions",
    # types for zero-terminated arrays we probably don't want
    "OSTree.CollectionRefv",
    "OSTree.RepoFinderResultv",
    # not part of the public interface, as far as I can tell
    "OSTree.Bootloader",
    "OSTree.BootloaderGrub2",
    "OSTree.BootloaderInterface",
    "OSTree.BootloaderSyslinux",
    "OSTree.BootloaderUboot",
    "OSTree.BootloaderZipl",
    "OSTree.ChecksumInputStream",
    "OSTree.ChecksumInputStreamBuilder",
    "OSTree.CmdPrivateVTable",
    "OSTree.GpgVerifier",
    "OSTree.LibarchiveInputStream",
    "OSTree.LzmaCompressor",
    "OSTree.LzmaDecompressor",
    "OSTree.RollsumMatches",
    # builders we don't want
    "OSTree.RepoBuilder",
    "OSTree.RepoFinderMountBuilder",
    "OSTree.SePolicyBuilder",
    "OSTree.SysrootBuilder",
    "OSTree.SysrootUpgraderBuilder",
]

[crate_name_overrides]
os_tree = "ostree"

[[object]]
name = "OSTree.CollectionRef"
status = "generate"
    [[object.function]]
    # helper functions for NULL-terminated arrays
    pattern = "dupv|freev"
    ignore = true

    [[object.function]]
    # clone() should already be this
    name = "dup"
    ignore = true

[[object]]
name = "OSTree.Repo"
status = "generate"
    [[object.function]]
    # this one generates a guchar** incorrectly
    name = "write_content_async"
    ignore = true

    [[object.function]]
    # these fail because of issues with arrays of dubious lifetimes
    pattern = "find_remotes_async|pull_from_remotes_async"
    ignore = true

    [[object.function]]
    # this is deprecated and supposedly unsafe for GI
    name = "checkout_tree_at"
    ignore = true

    [[object.function]]
    name = "checkout_at"
    [[object.function.parameter]]
    name = "options"
    const = true
    [[object.function.parameter]]
    name = "destination_path"
    string_type = "filename"

[[object]]
name = "OSTree.RepoFinder"
status = "generate"
    [[object.function]]
    # these fail because of issues with arrays of dubious lifetimes
    pattern = "resolve_async|resolve_all_async"
    ignore = true

[[object]]
name = "OSTree.RepoFinderResult"
status = "generate"
    [[object.function]]
    # array helper function
    name = "freev"
    ignore = true

    [[object.function]]
    # clone() should already be this
    name = "dup"
    ignore = true

[[object]]
name = "OSTree.RepoTransactionStats"
status = "generate"
init_function_expression = "|_ptr| ()"
clear_function_expression = "|_ptr| ()"

[[object]]
name = "OSTree.Sign"
status = "generate"
    [[object.function]]
    pattern = "dummy_.+|ed25519_.+"
    ignore = true

[[object]]
name = "OSTree.*"
status = "generate"
    [[object.function]]
    # low-level functions with unsafe APIs
    pattern = "cmp_checksum_bytes|checksum_inplace_to_bytes|hash_object_name"
    ignore = true

    [[object.function]]
    # private API
    pattern = "cmd__private__"
    ignore = true

    [[object.constant]]
    # version-dependent constants
    pattern = "VERSION|VERSION_S|YEAR_VERSION|RELEASE_VERSION"
    ignore = true

    [[object.constant]]
    # build-dependent constants
    pattern = "BUILT_FEATURES"
    ignore = true
