[options]
work_mode = "sys"
library = "OSTree"
version = "1.0"
target_path = "../sys"
external_libraries = [
   "GLib",
   "GObject",
   "Gio",
]
ignore = [
    "OSTree.BootloaderInterface",
    "OSTree.ChecksumInputStream",
    "OSTree.ChecksumInputStreamClass",
    "OSTree.CmdPrivateVTable",
    "OSTree.LibarchiveInputStream",
    "OSTree.LibarchiveInputStreamClass",
    "OSTree.LzmaCompressorClass",
    "OSTree.LzmaDecompressorClass",
    "OSTree.RepoFileEnumeratorClass",
    "OSTree.RollsumMatches",
    "OSTree.RELEASE_VERSION",
    "OSTree.VERSION",
    "OSTree.VERSION_S",
    "OSTree.YEAR_VERSION",
]

girs_dir = "../gir-files"
