name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: quay.io/coreos-assembler/fcos-buildroot:testing-devel

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --features=v2021_3
    - name: Run tests
      run: cargo test --verbose --features=v2021_3
